name: Full VPS (Ubuntu)

on:
  workflow_dispatch:   # Run manually from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup VPS Environment
        run: |
          echo "===================================="
          echo "🚀 Your VPS is starting on GitHub..."
          echo "===================================="

          # Show system info
          uname -a
          echo "------------------------------------"
          lsb_release -a || cat /etc/os-release
          echo "------------------------------------"
          echo "CPU cores: $(nproc)"
          echo "------------------------------------"
          free -h
          echo "------------------------------------"
          df -h
          echo "===================================="

          # Install basic tools
          sudo apt-get update -y
          sudo apt-get install -y \
            curl wget unzip git htop screen tmux net-tools \
            build-essential software-properties-common

          echo "===================================="
          echo "📦 Installing Programming Languages..."
          echo "===================================="

          # Python
          sudo apt-get install -y python3 python3-pip
          python3 --version
          pip3 --version

          # Node.js (LTS)
          curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node -v
          npm -v

          # Java
          sudo apt-get install -y openjdk-17-jdk
          java -version

          echo "===================================="
          echo "✅ VPS is Ready!"
          echo "👉 You can now run your own commands/scripts here"
          echo "===================================="

      - name: Example Commands (Edit This)
        run: |
          echo ">>> Running Example Commands..."
          python3 -c "print('Hello from Python!')"
          node -e "console.log('Hello from Node.js!')"
          javac -version

      - name: Keep VPS Alive (6 hours)
        run: |
          echo "Keeping VPS alive for 6 hours..."
          sleep 21600
